{
  config,
  pkgs,
  lib,
  ...
}:
let
  # Match the configuration file generated by the upstream cscli wrapper.
  crowdsecConfigFile =
    (pkgs.formats.yaml { }).generate "crowdsec.yaml"
      config.services.crowdsec.settings.general;
in
{
  # Allow remote CrowdSec diagnostics without sharing a sudo password.
  # Keep arguments exact: unrestricted cscli also permits state changes.
  security.sudo.extraRules = [
    {
      users = [ "zeno" ];
      runAs = config.services.crowdsec.user;
      commands =
        map
          (args: {
            command = "${config.services.crowdsec.package}/bin/cscli -c=${crowdsecConfigFile} ${args}";
            options = [ "NOPASSWD" ];
          })
          [
            "metrics"
            "metrics show acquisition"
            "bouncers list"
            "alerts list"
            "alerts list -o json"
            "decisions list"
            "console status"
            "parsers inspect crowdsecurity/traefik-logs"
            "collections list"
            "scenarios list"
            "appsec-configs list"
            "appsec-rules list"
            "metrics show appsec"
            "simulation status"
            "hub list"
            "hub upgrade --dry-run"
          ];
    }
  ];

  # Observe WAF matches before promoting rules to enforcement. Suppress both
  # inline blocking and events that could create a later IP ban. Keep alerts.
  environment.etc."crowdsec/appsec-configs/blizzard-observe.yaml".source =
    (pkgs.formats.yaml { }).generate "blizzard-appsec-observe.yaml"
      {
        name = "local/blizzard-observe";
        default_remediation = "allow";
        inband_rules = [
          "crowdsecurity/base-config"
          "crowdsecurity/vpatch-*"
        ];
        on_match = [
          {
            apply = [
              "SetRemediation(\"allow\")"
              "SetReturnCode(200)"
              "CancelEvent()"
              "SendAlert()"
            ];
          }
        ];
      };

  # Hub installation runs as CrowdSec and must be able to create rule links.
  # environment.etc creates the custom config's parent as root on first boot.
  systemd.tmpfiles.rules = [
    "d /etc/crowdsec/appsec-configs 0750 ${config.services.crowdsec.user} ${config.services.crowdsec.group} -"
    "d /etc/crowdsec/appsec-rules 0750 ${config.services.crowdsec.user} ${config.services.crowdsec.group} -"
  ];

  systemd.services = {
    # Upstream module clears PATH entirely (`path = lib.mkForce []`).
    # Without this, CrowdSec starts but silently skips the journalctl acquisition
    # (CanRun → exec.LookPath fails → DataSourceUnavailableError → logged and skipped).
    crowdsec.path = lib.mkForce [ pkgs.systemd ];

    # Refresh the catalogue and report available upgrades, without mutating the
    # running ruleset. The upstream timer tries to reload a non-reloadable unit.
    crowdsec-update-hub.serviceConfig.ExecStartPost = lib.mkForce [
      "${config.services.crowdsec.package}/bin/cscli -c=${crowdsecConfigFile} hub upgrade --dry-run"
      "${pkgs.python3}/bin/python3 ${../../../packages/crowdsec-observability/hub-status.py} ${config.services.crowdsec.package}/bin/cscli ${crowdsecConfigFile}"
    ];

    # Run before the engine's setup/test commands. Only remove obsolete links
    # generated by Nix; preserve administrator-owned files and other symlinks.
    crowdsec-contexts = {
      before = [ "crowdsec.service" ];
      requiredBy = [ "crowdsec.service" ];
      after = [ "systemd-tmpfiles-setup.service" ];
      serviceConfig = {
        Type = "oneshot";
        User = config.services.crowdsec.user;
        Group = config.services.crowdsec.group;
        ExecStart = "${pkgs.python3}/bin/python3 ${../../../packages/crowdsec-observability/contexts.py} /etc/crowdsec/contexts ${
          pkgs.writeText "crowdsec-context-targets.json" (
            builtins.toJSON (
              map (
                context: toString ((pkgs.formats.yaml { }).generate "context.yaml" context)
              ) config.services.crowdsec.localConfig.contexts
            )
          )
        }";
        ProtectSystem = "strict";
        ReadWritePaths = [ "/etc/crowdsec/contexts" ];
        ProtectHome = true;
        PrivateTmp = true;
        NoNewPrivileges = true;
      };
    };

  };

  services.crowdsec-firewall-bouncer = {
    enable = true;
    registerBouncer.enable = false;
    secrets.apiKeyPath = config.sys.secrets.crowdsecFirewallBouncerTokenFile;
    settings = {
      # Host INPUT only: do not change MicroVM forwarding or WireGuard policy.
      iptables_chains = [ "INPUT" ];
      prometheus = {
        enabled = true;
        listen_addr = "127.0.0.1";
        listen_port = 6061;
      };
    };
  };

  services.crowdsec = {
    enable = true;
    autoUpdateService = true;

    settings = {
      simulation = {
        simulation = false;
        exclusions = [
          "crowdsecurity/http-dos-bypass-cache"
          "crowdsecurity/http-dos-random-uri"
          "crowdsecurity/http-dos-switching-ua"
          "crowdsecurity/http-dos-invalid-http-versions"
        ];
      };
      lapi.credentialsFile = "/var/lib/crowdsec/state/local_api_credentials.yaml";
      capi.credentialsFile = "/var/lib/crowdsec/state/online_api_credentials.yaml";

      console = {
        tokenFile = config.sys.secrets.crowdsecConsoleTokenFile;

        configuration = {
          share_manual_decisions = true;
          share_custom = true;
          share_tainted = true;
          share_context = true;
          console_management = true;
        };
      };

      general.api.server = {
        enable = true;
        listen_uri = "127.0.0.1:8085";
      };
    };

    hub = {
      collections = [
        "crowdsecurity/linux"
        "crowdsecurity/traefik"
        "crowdsecurity/http-cve"
        "crowdsecurity/whitelist-good-actors"
        "crowdsecurity/http-dos"
        "crowdsecurity/appsec-virtual-patching"
      ];

      scenarios = [
        "crowdsecurity/ssh-bf"
        "crowdsecurity/ssh-slow-bf"
        "crowdsecurity/http-crawl-non_statics"
        "crowdsecurity/http-probing"
        "crowdsecurity/http-sensitive-files"
        "crowdsecurity/http-bad-user-agent"
      ];

      postOverflows = [
        "crowdsecurity/auditd-nix-wrappers-whitelist-process"
        "crowdsecurity/cdn-whitelist"
      ];
    };

    localConfig = {
      acquisitions = [
        {
          source = "appsec";
          listen_addr = "127.0.0.1:7422";
          appsec_configs = [ "local/blizzard-observe" ];
          labels.type = "appsec";
        }
        {
          source = "journalctl";
          journalctl_filter = [ "_SYSTEMD_UNIT=sshd.service" ];
          labels.type = "syslog";
        }
        {
          source = "journalctl";
          journalctl_filter = [
            "_SYSTEMD_UNIT=traefik.service"
            # The Traefik parser needs the JSON MESSAGE without journal prefixes.
            "--output=cat"
            # Exclude plugin security events and application diagnostics from
            # the HTTP parser. These are archived through Alloy separately.
            "--grep=^\\{.*\"ClientHost\":"
          ];

          labels = {
            type = "traefik";
            service = "traefik";
            environment = "production";
          };
        }
      ];

      contexts = [
        {
          context = {
            target_host = [ "req != nil ? req.Host : evt.Meta.target_fqdn" ];
            target_uri = [ "req != nil ? req.URL.Path : evt.Meta.http_path" ];
            http_method = [ "req != nil ? req.Method : evt.Meta.http_verb" ];
            http_status = [ "evt.Meta.http_status" ];
            user_agent = [ "req != nil ? req.UserAgent() : evt.Meta.http_user_agent" ];
          };
        }
      ];

      profiles = [
        {
          name = "default_ip_remediation";
          filters = [ "Alert.Remediation == true && Alert.GetScope() == 'Ip'" ];
          # Count retained decisions from the last week, capped at one day.
          # Database retention also bounds how much history is available.
          duration_expr = "Sprintf('%dh', min(24, (GetDecisionsSinceCount(Alert.GetValue(), '168h') + 1) * 4))";

          decisions = [
            {
              type = "ban";
              duration = "4h";
            }
          ];
          on_success = "break";
        }
      ];
    };
  };
}
