
name: CI
on:
  push:
    branches: [main, testing]
  pull_request:
    branches: [main, testing]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: DeterminateSystems/nix-installer-action@main
      - name: Run Tests
        run: nix flake check