name: Comment and auto-merge
on:
  workflow_call:
    secrets:
      github_token:
        required: true
    inputs:
      pull_request_operation:
        type: string
        required: true
      pull_request_url:
        type: string
        required: false

jobs:
  comment_and_automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Create compare URLs
        if: ${{ inputs.pull_request_operation == 'created' || inputs.pull_request_operation == 'updated' }}
        uses: actions/github-script@main
        with:
          github-token: ${{ secrets.github_token }}
          script: |
            const comment = require('.github/scripts/comment')
            const compare = require('.github/scripts/compare')

            const urls = await compare({ core })
            if (!urls?.length) return

            const header = "# Compare URLs"
            const body = urls.map((url) => `- ${url}`).join("\n")

            const issueNumber = parseInt(process.env.PULL_REQUEST_NUMBER, 10)
            if (Number.isNaN(issueNumber)) return

            await comment({ github, context, header, body, issueNumber })

      - name: Auto-merge GitHub bot PRs
        if: ${{ inputs.pull_request_url != '' }}
        run: |
          if [ -n "$PR_URL" ]; then
            gh pr merge --auto --merge "$PR_URL"
          else
            echo "PR_URL is not set!"
          fi
        env:
          PR_URL: ${{ inputs.pull_request_url }}
          GH_TOKEN: ${{ secrets.github_token }}
