
name: Lint
on:
  pull_request:
    branches: [main, testing]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: DeterminateSystems/nix-installer-action@main
      - name: Run linter
        run: nix shell nixpkgs#nixpkgs-fmt -c nixpkgs-fmt --check .